### ISSUE TITLE
Using SkeletonRecyclerView

### ISSUE THREAD

**Issue by alekseyHunter** [AgnaldoNP/AGSkeletonLoading#3]
Hello!

I get next error, when I make project:

> gradle\caches\transforms-2\files-2.1\9920a4a435549618c3716b3c44a0b094\jetified-AGSkeletonLoading-1.0\res\values\values.xml:23:5-43:25: AAPT: error: duplicate value for resource 'attr/duration' with config ''.

    
Changed the name attribute, but error not hidden.

**Comment by AgnaldoNP** [comment]
try to clear gradle and Android Studio's cache, I changed the attribute name in the last version (1.1) and this error disappeared for me.

**Comment by Benjf29** [comment]
> try to clear gradle and Android Studio's cache, I changed the attribute name in the last version (1.1) and this error disappeared for me.

Hi
I have the same issue with  version 1.1, I've clear Gradle cache & android studio cache but issue still here (same with v1.0)
